spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

jwt.secret=${JWT_SECRET}

# Mail ? hardcoded, these never change
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=false

app.email.dev-mode=${APP_EMAIL_DEV_MODE:false}
server.port=${PORT:8080}
springdoc.swagger-ui.path=/swagger-ui.html